x-service-base: &service-base
  build:
    context: .
  env_file:
    - .env
  depends_on:
    alembic:
      condition: service_started
    postgres:
      condition: service_started
    rabbitmq:
      condition: service_healthy

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres
      -c log_statement=all
      -c log_duration=on
      -c log_min_duration_statement=0
      -c logging_collector=off
      -c client_min_messages=log
      -c log_error_verbosity=default
    restart: unless-stopped

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  backend:
    <<: *service-base
    command: python -m services.backend
    depends_on:
      redis:
        condition: service_started
      fill_db:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    profiles:
      - with_backend
    restart: unless-stopped

  bot:
    <<: *service-base
    command: python -m services.bot
    depends_on:
      fill_db:
        condition: service_completed_successfully
    profiles:
      - with_bot
    restart: unless-stopped

  fill_db:
    <<: *service-base
    command: python -m services.fill_db

  alembic:
    build:
      context: .
    command: alembic -c services/alembic/alembic.ini upgrade head
    restart: no
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./services/frontend
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_started
    profiles:
      - with_frontend
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      frontend:
        condition: service_started
    profiles:
      - with_frontend
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
