
services:
  backend:
    build: .
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/vpn_db
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - rabbitmq
      - redis
    ports:
      - "8000:8000"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vpn_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pg_data:
